import Categories from "@/components/Categories";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dua App",
  description: "Generated by create next app",
};

export default function DuaLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Sidebar />
      <div className="flex ml-28 flex-col lg:flex-row">
        <Categories />
        {children}
      </div>
    </div>
  );
}
